spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: servicecloud-config-dev
---
spring:
  profiles: test
  application:
    name: servicecloud-config-test
#    保存格式必须是UTF-8